# Generated by Django 5.0.2 on 2025-01-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_available_room_units_blog_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_no',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
