# Generated by Django 5.1.4 on 2025-01-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_room_price_alter_room_units_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
