# Generated by Django 5.1.4 on 2025-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_activities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
