# Generated by Django 5.1.4 on 2025-01-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_about_mission_alter_about_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
