# Generated by Django 5.1.4 on 2025-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_address_contact_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='room',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
