# Generated by Django 5.1.4 on 2025-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_reservation_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
