# Generated by Django 5.1.4 on 2025-01-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_reservation_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
